### ISSUE TITLE
It doesn't work with MULTIRES VTOUR

### ISSUE THREAD

**Issue by eliecermarchante** [lonelyelk/krpano-arrows#1]
It seems to don't work with MULTIRES VTOUR.

**Comment by lonelyelk** [comment]
Can you provide an example? I have several working projects with multires cubic panoramas both in one xml with several scenes and in multiple xml.

**Comment by eliecermarchante** [comment]
This is a test example: http://your360virtual.com/vtour/tour.html

**Comment by eliecermarchante** [comment]
link to arrows.xml: http://your360virtual.com/vtour/arrows.xml 
link to tour.xml: http://your360virtual.com/vtour/tour.xml

**Comment by lonelyelk** [comment]
Ok, I see. This has to do with layers being discarded when outside `<scene>` tags. I am committing a fix right now and in your case you should also add `keep="true"` to both _custom-arrow-shape_ and _line-shape_ layers. Otherwise when `loadscene()` is called all layers outside the `<scene>` tag and without `keep="true"` attribute get erased. As well as my default arrow shape.

**Comment by eliecermarchante** [comment]
I still don't see the arrows.

**Comment by eliecermarchante** [comment]
I also tried with krpano 1.18.5 obtaining the same results.

**Comment by lonelyelk** [comment]
Can you upload fixed version to the same host?

**Comment by eliecermarchante** [comment]
It's what I'm doing now.

**Comment by lonelyelk** [comment]
arrows.xml must have `<layer name="default-arrow-shape" keep="true">` too

**Comment by eliecermarchante** [comment]
Using krpano 1.18.5:   http://your360virtual.com/krpano1-18-5/tour.html
Using krpano 1.19.pr3:  http://your360virtual.com/krpano1-19-pr3/tour.html

**Comment by eliecermarchante** [comment]
Only one arrow is displayed and I declared 3.

**Comment by lonelyelk** [comment]
1.18 doesn't have arrows included in xml. And in 1.19 I see arrows. The reason there is only one is because the three you declared have the same name. In krpano tags with the same name in the same level override each other and the one you see is the last declared with the same name.

**Comment by eliecermarchante** [comment]
There are arrows in both. Refresh the page.
It looks like the last arrow is the one displayed and not all of them. If I remove the last 2, then the first one is displayed.

**Comment by lonelyelk** [comment]
As I said above, try using different `name` attribute.

**Comment by eliecermarchante** [comment]
Sorry. My bad. That did the trick.
