### ISSUE TITLE
How to edit arrows using action

### ISSUE THREAD

**Issue by mudin3i** [lonelyelk/krpano-arrows#3]
Hello,

I cannot generate arrows using my js code.
I dont know how to add <connection/> element to my connections layer.
Do you have any action for this?

Best ragards,

Mudin

**Comment by lorenzrings** [comment]
Hi Mudin,
check this. Maybe it helps you.

```
krpano().call('set(layer[connections].connection['+spotName+'].hdir,'+pos.h+')');
krpano().call('set(layer[connections].connection['+spotName+'].onclick, js(runHotspotAction('+spotId+')))');
```

**Comment by mudin3i** [comment]
I will check it very soon! thanks

**Comment by mudin3i** [comment]
it works! Thank you! 

one more issue,but not related to this plugin.
After adding new arrow, I am trying change its hdir using js, 
but it doesn't refresh in the scene, if I hover the arrow, or change view, then it refreshes.
What could be the reason for this?

**Comment by mudin3i** [comment]
I tried to call scenePlayer.krpano.call('updateConnections()');
but no luck :(

**Comment by lonelyelk** [comment]
Hello, Mudin!
Some time ago I noticed that separate `krpano.call()` are processed separately and concurrently. So first thing you need to do is to make adjustments in one call. But there is more. To reproduce your on my setup problem I tried:

``` javascript
setTimeout(function () {
    document.getElementById('krpanoSWFObject')
        .call('add(layer[connections].connection[scene3].hdir, 90);events.dispatch(onviewchange);');
}, 2000);
```

But it only moved a shadow. I could not trigger hotspot redraw for some reason. So I found a solution:

``` javascript
setTimeout(function () {
    document.getElementById('krpanoSWFObject')
        .call('add(layer[connections].connection[scene3].hdir, 90);add(view.hlookat, 0.000001);');
}, 2000);
```

**Comment by lonelyelk** [comment]
I beleive monkeypatch above with `add(view.hlookat, 0.000001);` fixes the issue.

**Comment by mudin3i** [comment]
hi, Sergey

Thank you for your solution.
I appreciate it :)

Mudin
