### ISSUE TITLE
Arrow Icon

### ISSUE THREAD

**Issue by mudin3i** [lonelyelk/krpano-arrows#4]
Hello again,

sorry for asking too much.

Is it possible to use png/svg icons as an arrow?
Like this:

![screen shot 2016-05-23 at 5 42 44 pm](https://cloud.githubusercontent.com/assets/15241252/15465145/1001e20e-210e-11e6-9778-7e3635368d77.png)

**Comment by lonelyelk** [comment]
In this case you need something different. This is probably the closest solution: http://krpano.com/forum/wbb/index.php?page=Thread&threadID=6655

**Comment by mudin3i** [comment]
hi, Yeah I got it! I will try to make it.
Thank you
